language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
python:
  - "3.5"
install:
  - pip install --user awscli
script:
  - npm install
  - npm run eslint
  - npm run csslint
  - npm run test-ci
  - ./deploy-to-s3.sh
env:
  secure: "ql/KPP1QlGMC41DXyA+L8UATiauYFkFcwCpfF1C2qsPNz4rYCpmOxuX+fpeedgcsbboubVZ7IaZjRdRIN18cfe/aIXT5Tm8e4hKUItZCR2fbXN2t4PEN2tegV9BQ9/lcjuc3jZ5128SYGGcMp2Zp4y0ThmOwFEWTbLSAEA1KA5KvLjXzIYoJLUnO3sxU45JTrp+wmSexBX6HKNvKUhbVSGWbg2aYtLvoxnUOmJIpBcs5eXffyb13xcBCnbIlYMoZlGzX70bK+75xMkAV1IsSzdBHplirVpUMGPhKd0KiFjtzUJXeyXaZkq9GbM7GMq6WkLo15Evvt/gjU6Es25Hwnnw55ANuzkRj6ll6Lbmjxf1Is/DRXO7x1mLYVewWH412fWIl4zFMSTo+b1yo9DBDFkre8mR0oRgyhu8/xUgKRrcxP2U8VCnxyP6xof0OW/7c+zDBKOdmpoqmVRjVldeqKacyMMgGD0ywamOcwmgxMVNfSDwckhNNr2fVu5d3Ykt0tvF5LZ6EVWlfmnipQJy3QNVr1wV108GlJ0ys8J1Twg8wRJnddT1VdhmsTPS/GXA4ynn3O2DfodaTmTG5Hbi312MA7VE6uYGuPv05QYPKTpVh9FJFNmNNusmi1i//MXo7fh07J2EJMyiSyyZ+ywsGSKDqgocyjhPjekxFf4UCIZU="