language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
python:
  - "3.5"
install:
  - pip install --user awscli
script:
  - npm install
  - npm run eslint
  - npm run csslint
  - npm run test-ci
  - ./deploy-to-s3.sh
env:
  secure: "U7ifpSfevxDKizqX9RGJffiGKJ/geGXPuKbLFqnLKdoXLFi8AsGjPDV689EVr3xaIVr/FIfIsCoyCwIfKMIZOfqjM8q15LGD9iVZbZKHs567nhV3hOZKe0S1+tshUj9/RcMK2aX3X9vjR/DHrQroP/F/Q7OCstvAVNcG2EjY67x0rZdldp+6BwA5WtspuQSdI0qR5TcIfMri8NDRfSaDMaUUaL03P77bS0yGGz0k2J3MDiaE0L2Cur6eI+cM2kLNc7luRiZcc7Uq0KnxilklO5mB8deASRceFEojLbMiKY9fWoU+IhwKFrsFJlMC+BWYfzVlxg7BOZwABI3T0XKBigWUfFWKvLPlKWzFfEyBxY9QToTKEPO/PIBRWOGDWZyYRpYYYzusJObnGhX9fDW+LjTwPj2aylwC9dtcqQRKdXDTjcW8UXxiNp2VIUmtAb004CsLesFyla9RaW4L86IfydElnAxCDQ3OVybFqjOi3cZLP/tVulvcapzicYJ7aEXENezIbSfP2EuKdLlB9MHSWu1hYwBXotdztTJb07DFjcqrmZckKcnkL1thieLGjAaB0Rvr83BHtEeAi7RmHLFI/mLcDplkDyMlqZV4lZd5Wwq9t1kbyZq0suxZ8UV0vCojNIKvaKJ3JWl6eEzh5+TdNdyYc5Hx6tM5Kfi7MayDqlc="