language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
python:
  - "3.5"
install:
  - pip install --user awscli
script:
  - npm install
  - npm run eslint
  - npm run csslint
  - npm run test-ci
  - ./deploy-to-s3.sh
env:
  secure: "ckgvvjJXVak0KcKyf+bj6EKbGHkUyIIHsJvVqEOy5rB9As1mrfOXgOqJHndKQLd1Dpc5PV8fLwKfA6P99rnXKmfd5EtCAq4mkYmcrA7mwikQ8LN3o1uTaepr/EgPiEdlMGBnoU/lu5V7pcgxz4qsKJc/UK2ITYIZKQf49roj6k37b5CV6tlT8eByFm29ci2/x9YaixD+dqBqWhn/rwdg6zofWI29eW3vOQbJvsMGnOS98/25YLZTGWfYlgI0lLtPgq0g/7KW1qK3/WkIwz76gtDJo5q0Weg8BZAU93UJpHpFR/AZF59uP+kG6JYq0mOuKmpws2j6vuyi8HKivZ0SHvq6jQHaVIf+e+BHkmI4gATuw+1Ou/Ed0nfUW610oJyaLjQXCBN7q7p23+wzSGZuZ0ui56dwdHqiYRgGLcSS50zY7jpZ1ZJbgntsNxWhpZHqrDsAeElYNjdnM/EbVd4UNN6rswb5K2WFCc5P42zBJWre9miIL4EPeS3FjyOeVG+Kot5fzwK5segO6V5OwPleQuOETDzQdCqRaSNYdlq3R7P8k63SYBOuHXsTSBDxSveF14lREz2dw8SCSGnXJn8ofZj1olnWbqgFNXY7YI4JdMhzw+ce8CnVUscAEEbW3X4gMUKAL6fKzm/Qaua0INXfDiuCniZUxwXocCKby8UbyG8="
