language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
python:
  - "3.5"
install:
  - pip install --user awscli
script:
  - npm install
  - npm run eslint
  - npm run csslint
  - npm run test-ci
  - ./deploy-to-s3.sh
env:
  secure: "oyzY28ZDPTg445ZfWyK6XI84sqDdj7L4Ribh/yaLNABJbxIXkWgL6ehRJrRGWk4hwIbEVPKYQN2r4cwkyJJQ50X0AH20c7LifllrEUEXTjKFPekY48w+Gy+Sv1ydBbJHqP2nFusy0ZEs4o5P2WjVCieE7604Pd3bJQd6qXM4krR7OtuyqLgGYpd8OQqtJajsevjY8NfR3y6te/6udK2KVo2IvH87H3jYLnO/huAA+bGpZp8Ob2q1uvdMCLkcw+iqATrz6UowzO/d1ieEjZ5Ut0kOYi81LAPEMkEP+0JHPB4N1H8pV4uVLO3IGGEKdtQUJ4nHuzPXCAQpsdqUgq+6xx3qXYaG2Y0egdNVceR+FU2RFuTBkrkT4YLYKgwZGxW4RsxoB+fyb1TZ89mgfKo/47n1+IQl9z7L34chamCB55Ze19a0W8bkOdXhfJK/IsWpwF1nF870Sq301F9DEks/fWanRCPaa7b2DE/BeSxY1i2FwYL3I4MJDMmx42Z7+n1SCTBWmpsfA8QrhU1+zW29Wv6k4XB+y3KDVALkWSPUvu5xc3aLosMijGUeOYRFWiMJy95C69cAaFHhPPpgkopy61DTdZUFgAD4VFxpCdzulOtrfrgBTPMMD6SpKGpH0uRppvZ77k9HFJG2DGJrQuXE13gkNWuUcj6I0KVbbaX/oEQ="